# Generated by Django 5.1.6 on 2025-02-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='duration',
            field=models.CharField(choices=[('Single Day', 'Single Day'), ('Multiple Days', 'Multiple Days'), ('First Half', 'First Half'), ('Second Half', 'Second Half')], default='Single Day', max_length=25),
        ),
    ]
