# Generated by Django 5.1.6 on 2025-02-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leave_approved_by_leave_approved_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='approved_by',
            new_name='actioned_by',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='approved_on',
            new_name='actioned_on',
        ),
    ]
