# Generated by Django 5.1.6 on 2025-02-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_employee_id_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profilepics'),
        ),
    ]
