# Generated by Django 5.1.6 on 2025-02-14 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PUNCHEDIN', 'PUNCHEDIN'), ('PUNCHEDOUT', 'PUNCHEDOUT')], max_length=20)),
                ('punch_in_time', models.TimeField()),
                ('punch_out_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
