# Generated by Django 5.1.6 on 2025-02-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='session_working_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
