# Generated by Django 5.1.6 on 2025-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0002_punch_session_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='punch_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punch',
            name='punch_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
