# Generated by Django 5.1.6 on 2025-02-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0005_alter_punch_punch_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='punch_in_time',
            field=models.DateTimeField(),
        ),
    ]
