# Generated by Django 5.1.6 on 2025-02-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0007_alter_punch_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
