# Generated by Django 5.1.6 on 2025-02-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0008_alter_punch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='punch_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
