# Generated by Django 5.1.6 on 2025-02-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0012_alter_punch_punch_out_time_alter_punch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='punch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='punch',
            name='punch_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punch',
            name='punch_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punch',
            name='status',
            field=models.CharField(choices=[('PUNCHEDIN', 'PUNCHEDIN'), ('PUNCHEDOUT', 'PUNCHEDOUT')], max_length=20),
        ),
    ]
