# Generated by Django 5.1.6 on 2025-02-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='working_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
