# Generated by Django 5.1.6 on 2025-02-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_punch_in_alter_attendance_punch_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.DateTimeField(),
        ),
    ]
