# Generated by Django 5.1.6 on 2025-02-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_punch_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
