# Generated by Django 5.1.6 on 2025-02-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_punch_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present'), ('Late', 'Late'), ('Leave', 'Leave')], default='Absent', max_length=15),
        ),
    ]
