# Generated by Django 5.1.6 on 2025-02-17 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_rename_status_attendance_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
