# Generated by Django 5.1.6 on 2025-02-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendance_punch_in_alter_attendance_punch_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
