# Generated by Django 5.1.6 on 2025-02-17 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_attendance_punch_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
