# Generated by Django 5.1.6 on 2025-02-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendance_working_hours_frompunch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='working_hours_frompunch',
            new_name='working_hours_today',
        ),
    ]
